name: "Prepare rust environment"
description: "Sets up all environmental variables and ssh, potentially also container registry"
inputs:
  ssh_auth_sock:
    description: "SSH socket"
    default: "/tmp/ssh_agent.sock"
    required: true
  cargo_home:
    description: "Cargo home"
    default: ".cargo"
  famedly_crate_registry:
    description: "Whether to enable the Famedly crate registry"
    required: false
    default: "false"
  famedly_crate_registry_name:
    description: "Crate registry name"
    default: "famedly"
  famedly_crate_registry_index:
    description: "URL of crate registry index"
    default: "ssh://git@ssh.shipyard.rs/famedly/crate-index.git"
  famedly_crate_registry_index_ssh_privkey:
    description: "SSH private key for authenticating with crate registry index"
    required: false
  additional_packages:
    description: "Additional package to install during preparation"
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        SSH_AUTH_SOCK: ${{ inputs.ssh_auth_sock }}
        FAMEDLY_CRATE_REGISTRY_INDEX_SSH_PRIVKEY: ${{ inputs.famedly_crate_registry_index_ssh_privkey }}
      run: $GITHUB_ACTION_PATH/prepare_ssh.sh

    - shell: bash
      env:
        CARGO_HOME: ${{ inputs.cargo_home }}
        ADDITIONAL_PACKAGES: ${{ inputs.additional_packages }}
        FAMEDLY_CRATE_REGISTRY_ENABLED: ${{ inputs.famedly_crate_registry_enabled}}
        FAMEDLY_CRATE_REGISTRY_NAME: ${{ inputs.famedly_crate_registry_name }}
        FAMEDLY_CRATE_REGISTRY_INDEX: ${{ inputs.famedly_crate_registry_index }}
      run: $GITHUB_ACTION_PATH/prepare_rust.sh
