name: "Prepare rust environment"
description: "Sets up all environmental variables and ssh, potentially also container registry"
inputs:
  ssh_auth_sock:
    description: "SSH socket"
    default: "/tmp/ssh_agent.sock"
    required: true
  cargo_home:
    description: "Cargo home"
    default: ".cargo"
  gitlab_ssh:
    description: "CI_SSH_PRIVATE_KEY (should be renamed but requires a lot of chores)"
    required: true
  famedly_crates_registry:
    description: "Famedly registry name"
    default: "famedly"
  famedly_crates_registry_index:
    description: "URL of famedly registry index"
    default: "ssh://git@gitlab.com:22/famedly/company/devops/crates-index.git"
  additional_packages:
    description: "Additional package to install during preparation"
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        SSH_AUTH_SOCK: ${{ inputs.ssh_auth_sock }}
        CI_SSH_PRIVATE_KEY: ${{ inputs.gitlab_ssh }}
      run: $GITHUB_ACTION_PATH/prepare_ssh.sh

    - shell: bash
      run: $GITHUB_ACTION_PATH/prepare_git.sh

    - shell: bash
      env:
        CARGO_HOME: ${{ inputs.cargo_home }}
        ADDITIONAL_PACKAGES: ${{ inputs.additional_packages }}
        FAMEDLY_CRATES_REGISTRY: ${{ inputs.famedly_crates_registry }}
        FAMEDLY_CRATES_REGISTRY_INDEX: ${{ inputs.famedly_crates_registry_index }}
      run: $GITHUB_ACTION_PATH/prepare_rust.sh
