name: "Prepare rust environment"
description: "Sets up all environmental variables and ssh, potentially also container registry"
inputs:
  ssh_auth_sock:
    description: "SSH socket"
    default: "/tmp/ssh_agent.sock"
  cargo_home:
    description: "Cargo home"
    default: ".cargo"
  crate_registry_name:
    description: "Famedly registry name"
    default: "famedly"
  crate_registry_index_url:
    description: "URL of famedly registry index"
    default: "ssh://git@ssh.shipyard.rs/famedly/crate-index.git"
  crate_registry_ssh_privkey:
    description: "SSH private key for authenticating with famedly registry index. This needs to be set for a private registry to be configured."
  additional_packages:
    description: "Additional package to install during preparation"
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        SSH_AUTH_SOCK: ${{ inputs.ssh_auth_sock }}
        CARGO_HOME: ${{ inputs.cargo_home }}
        ADDITIONAL_PACKAGES: ${{ inputs.additional_packages }}
        CRATE_REGISTRY_NAME: ${{ inputs.crate_registry_name }}
        CRATE_REGISTRY_INDEX_URL: ${{ inputs.crate_registry_index_url }}
        CRATE_REGISTRY_SSH_PRIVKEY: ${{ inputs.crate_registry_ssh_privkey }}
      run: $GITHUB_ACTION_PATH/prepare.sh
