name: Docker test

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test_root:
    uses: ./.github/workflows/docker-backend.yml
    secrets: inherit
    with:
      name: backend_build_workflows
  test_subfolder:
    uses: ./.github/workflows/docker-backend.yml
    with:
      path: subfolder
      name: subfolder
    secrets: inherit
  test_subsubfolder:
    uses: ./.github/workflows/docker-backend.yml
    with:
      path: subfolder/subsubfolder
      name: meow
    secrets: inherit

