name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
  pull_request:

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-a # -a should be removed, just for separate workflows in this repository
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always

# Defined CI jobs.
jobs:
  check:
    uses: ./.github/workflows/rust-workflow.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
