name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      additional_packages:
        description: 'Additional packages installed by workflow'
        default: ''
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  GITLAB_USER: ${{ secrets.GITLAB_USER }}
  GITLAB_PASS: ${{ secrets.GITLAB_PASS }}
  CARGO_HOME: "cargo_home"

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/famedly/rust-container:nightly
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        echo "https://${GITLAB_USER}:${GITLAB_PASS}@gitlab.com" >> ~/.git-credentials
        git config --global credential.helper store
        mkdir -p ${CARGO_HOME}
        apt-get install -yqq --no-install-recommends ${{ inputs.addtional_packages }}
        echo "[net]" >> ${CARGO_HOME}/config.toml
        echo "git-fetch-with-cli = true" >> ${CARGO_HOME}/config.toml
    - name: Check
      run: |
        cargo +${NIGHTLY_VERSION} fmt -- --check
        cargo lints clippy --workspace --all-targets -- -D warnings
        cargo llvm-cov nextest --workspace --ignore-filename-regex "cargo_home.*"
        cargo +${NIGHTLY_VERSION} test --doc --workspace --verbose
        cargo +${NIGHTLY_VERSION} udeps
    - name: Build
      run: cargo build --verbose --release
