name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-b # -b should be removed, just for separate workflows in this repository
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always
  ADDITIONAL_PACKAGES: ""

# Defined CI jobs.
jobs:
  check:
    runs-on: ubuntu-latest-16core
    container: ghcr.io/famedly/rust-container:nightly
    steps:
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/rust-prepare
        with:
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}
          additional_packages: ${{ env.ADDITIONAL_PACKAGES }}

      - name: Caching
        uses: Swatinem/rust-cache@b8a6852b4f997182bdea832df3f9e153038b5191

      - name: Rustfmt
        shell: bash
        run: cargo +${NIGHTLY_VERSION} fmt -- --check

      - name: Clippy
        shell: bash
        run: cargo lints clippy --workspace --all-targets -- -D warnings

      - name: Test & Coverage
        shell: bash
        run: cargo llvm-cov nextest --workspace --ignore-filename-regex "cargo_home.*"

      - name: Doc-test
        shell: bash
        run: cargo +${NIGHTLY_VERSION} test --doc --workspace

      - name: Udeps
        shell: bash
        run: cargo +${NIGHTLY_VERSION} udeps

      - name: Typos
        shell: bash
        run: typos # TODO: Use the typos action
