name: Rust workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always
  ADDITIONAL_PACKAGES: ""

# Defined CI jobs.
jobs:
  check:
    # This is set explictly to allow Meow-Coverage to post comments in response to Dependabot PRs which have a read-only GITHUB_TOKEN by default
    permissions:
      pull-requests: write
      issues: write
      contents: read
    runs-on: ${{ inputs.runs-on }}
    container: docker-oss.nexus.famedly.de/rust-container:nightly
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
      with:
        gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}
        gitlab_user: ${{ secrets.GITLAB_USER }}
        gitlab_pass: ${{ secrets.GITLAB_PASS }}

    - name: Caching
      uses: Swatinem/rust-cache@b8a6852b4f997182bdea832df3f9e153038b5191

    - name: Rustfmt
      shell: bash
      run: cargo +${NIGHTLY_VERSION} fmt -- --check

    - name: Clippy
      shell: bash
      run: cargo +${NIGHTLY_VERSION} clippy --workspace --all-targets -- -D warnings
    
    - name: Doc-test
      shell: bash
      run: cargo +${NIGHTLY_VERSION} test --doc --workspace --verbose

    - name: Udeps
      shell: bash
      run: cargo +${NIGHTLY_VERSION} udeps

    - name: Typos
      shell: bash
      run: typos

    - name: Test
      shell: bash
      run: cargo llvm-cov nextest --profile ci --workspace --lcov --output-path lcov.info

    - name: Codecov - Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        files: "lcov.info"

    - name: Codecov - Upload test results
      uses: codecov/test-results-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
