name: Docker test

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test-docker-backend-root:
    uses: ./.github/workflows/docker-backend.yml
    secrets: inherit
    with:
      name: backend_build_workflows_root
  test-docker-backend-subfolder:
    uses: ./.github/workflows/docker-backend.yml
    secrets: inherit
    with:
      path: subfolder
      name: backend_build_workflows_subfolder
  test-docker-backend-subsubfolder:
    uses: ./.github/workflows/docker-backend.yml
    secrets: inherit
    with:
      path: subfolder/subsubfolder
      name: backend_build_workflows_meow

