name: Docker test

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-docker-backend:
    uses: ./.github/workflows/docker-backend.yml
    secrets: inherit
    with:
      targets: foo,bar
